### ISSUE TITLE
Polyphony

### ISSUE THREAD

**Issue by ambs** [maxmcorp/mxm.midifile#3]
Hi
I was expecting that calling `note_on` different times with different notes would create a chord, but they are played sequentially. I even tried to call them with different channels, but that didn't work either.

Is there the possibility to do polyphony? In this case, I just wanted to play a chord.

Thank you

**Comment by maxmcorp** [comment]
Yes, set note_start at the same time for all the notes you want in the
chord.

Like set all the note_on for all the notes and then do an update time to
set the note_off for those same notest.

Hope my explanation is clear. I am currently on my phone.

tor. d. 17. dec. 2020 22.08 skrev Alberto Simões <notifications@github.com>:

**Comment by ambs** [comment]
Ah, I need to do an update time between each note as 0. Fixed! THanks
